version: 2.1
parameters:
  xcode-version:
    type: string
    default: "15.4.0"
  macos-resource-class:
    type: string
    default: macos.m1.medium.gen1

# Jobs -------------------------------------------------------------------------
jobs:
  build-and-test-xcframework:
    macos:
      xcode: << pipeline.parameters.xcode-version >>
    resource_class: << pipeline.parameters.macos-resource-class >>

    shell: /bin/bash --login -o pipefail

    steps:
      - run:
          name: check Xcode version and Python 3
          command: |
            /usr/bin/xcodebuild -version
            python3 --version
            python --version
            which python3
            echo $CIRCLE_WORKING_DIRECTORY
      - checkout
      - run:
          name: create directory to store the library
          command: |
            mkdir -p $HOME/onnxlibrary/macabi_release_v20230327_2320
      - run:
          name: install tools for build
          command: |
            brew install cmake
            pip install -r ${CIRCLE_WORKING_DIRECTORY}/requirements-dev.txt
      - run:
          name: build with build_apple_framework.py
          command: |
            export PYTHONPATH=${CIRCLE_WORKING_DIRECTORY}/tools/python:$PYTHONPATH
            python3 ${CIRCLE_WORKING_DIRECTORY}/tools/ci_build/github/apple/build_apple_framework.py --config Release --build_dynamic_framework  --build_dir=$HOME/onnxlibrary/macabi_release_v20230327_2320 \
              --include_ops_by_config=${CIRCLE_WORKING_DIRECTORY}/tools/ci_build/github/apple/hws_mobile_package.required_operators.config \
              ${CIRCLE_WORKING_DIRECTORY}/tools/ci_build/github/apple/default_full_ios_framework_build_settings.json

      - run:
          name: archive the build results
          command: |
            tar -cvf /Users/distiller/project/onnxruntime_xcf.tar -C $HOME/onnxlibrary/macabi_release_v20230327_2320/framework_out .

      - store_artifacts:
          path: /Users/distiller/project/onnxruntime_xcf.tar
          destination: onnxruntime_xcf.tar
workflows:
  version: 2
  build-and-test-xcframework:
    jobs:
      - build-and-test-xcframework
